import Head from 'next/head'
import { Inter } from '@next/font/google'
import MainLayout from '@/Layout/MainLayout'
import { NavigationMenu } from '@/components/NavigationMenu'
import { NextPage } from 'next'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <MainLayout>
          <h1>DefaultPage!</h1>
        </MainLayout>
      </main>
    </>
  )
}

export default Home
