'use-client'

import { Breadcrumb, Button, Carousel, Sidebar, Timeline } from 'flowbite-react'
import {
  CaretLeftIcon,
  CaretRightIcon,
  ChevronLeftIcon,
} from '@radix-ui/react-icons'
import { useEffect, useState } from 'react'

import { AspectRatio } from '@/components/ui/aspect-ratio'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { NextPage } from 'next'
import { Separator } from '@/components/ui/separator'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  const [themeColor, setThemeColor] = useState('dark')
  useEffect(() => {
    // On page load or when changing themes, best to add inline in `head` to avoid FOUC

    if (
      localStorage.theme === 'dark' ||
      (!('theme' in localStorage) &&
        window.matchMedia('(prefers-color-scheme: dark)').matches)
    ) {
      setThemeColor('dark')
    } else {
      setThemeColor('')
    }
  }, [themeColor])

  return (
    <div className={clsx(themeColor)}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main
        className={clsx(
          'flex min-h-screen flex-col items-center justify-center bg-rosePineDawn-base dark:bg-rosePineMoon-base',
        )}
      >
        <section
          className={clsx(
            'prose prose-zinc flex flex-col items-center justify-center dark:prose-invert',
            'lg:col-span-1 lg:h-full lg:w-full lg:items-start lg:justify-start lg:prose-xl',
          )}
        >
          <h1 className="px-10 pt-10 text-rosePineDawn-textos dark:text-rosePineMoon-textos">
            Goyo Hub
          </h1>
          <Breadcrumb aria-label="Default breadcrumb example">
            <Breadcrumb.Item>
              <Link href="/">Hub</Link>
            </Breadcrumb.Item>
            <Breadcrumb.Item>
              <Link href="/workHistory">Work</Link>
            </Breadcrumb.Item>
          </Breadcrumb>
          <div className={clsx('hidden', 'px-5 lg:flex lg:w-full')}>
            <Separator />
          </div>
          <Timeline className="prose prose-zinc m-10 flex flex-col items-center">
            <Timeline.Item>
              <Timeline.Point />
              <Timeline.Content>
                <Timeline.Time className="text-rosePineDawn-subtle dark:text-rosePineMoon-subtle">
                  February 2022
                </Timeline.Time>
                <Timeline.Title className="text-rosePineDawn-textos dark:text-rosePineMoon-textos">
                  Application UI code in Tailwind CSS
                </Timeline.Title>
                <Timeline.Body>
                  Get access to over 20+ pages including a dashboard layout,
                  charts, kanban board, calendar, and pre-order E-commerce &
                  Marketing pages.
                </Timeline.Body>
              </Timeline.Content>
            </Timeline.Item>
            <Timeline.Item>
              <Timeline.Point />
              <Timeline.Content>
                <Timeline.Time className="text-rosePineDawn-subtle dark:text-rosePineMoon-subtle">
                  February 2022
                </Timeline.Time>
                <Timeline.Title className="text-rosePineDawn-textos dark:text-rosePineMoon-textos">
                  Application UI code in Tailwind CSS
                </Timeline.Title>
                <Timeline.Body>
                  Get access to over 20+ pages including a dashboard layout,
                  charts, kanban board, calendar, and pre-order E-commerce &
                  Marketing pages.
                </Timeline.Body>
              </Timeline.Content>
            </Timeline.Item>
            <Timeline.Item>
              <Timeline.Point />
              <Timeline.Content>
                <Timeline.Time className="text-rosePineDawn-subtle dark:text-rosePineMoon-subtle">
                  February 2022
                </Timeline.Time>
                <Timeline.Title className="text-rosePineDawn-textos dark:text-rosePineMoon-textos">
                  Application UI code in Tailwind CSS
                </Timeline.Title>
                <Timeline.Body>
                  Get access to over 20+ pages including a dashboard layout,
                  charts, kanban board, calendar, and pre-order E-commerce &
                  Marketing pages.
                </Timeline.Body>
              </Timeline.Content>
            </Timeline.Item>
            <Timeline.Item>
              <Timeline.Point />
              <Timeline.Content>
                <Timeline.Time className="text-rosePineDawn-subtle dark:text-rosePineMoon-subtle">
                  March 2022
                </Timeline.Time>
                <Timeline.Title className="text-rosePineDawn-textos dark:text-rosePineMoon-textos">
                  Marketing UI design in Figma
                </Timeline.Title>
                <Timeline.Body>
                  All of the pages and components are first designed in Figma
                  and we keep a parity between the two versions even as we
                  update the project.
                </Timeline.Body>
              </Timeline.Content>
            </Timeline.Item>
            <Timeline.Item>
              <Timeline.Point />
              <Timeline.Content>
                <Timeline.Time className="text-rosePineDawn-subtle dark:text-rosePineMoon-subtle">
                  April 2022
                </Timeline.Time>
                <Timeline.Title className="text-rosePineDawn-textos dark:text-rosePineMoon-textos">
                  E-Commerce UI code in Tailwind CSS
                </Timeline.Title>
                <Timeline.Body>
                  Get started with dozens of web components and interactive
                  elements built on top of Tailwind CSS.
                </Timeline.Body>
              </Timeline.Content>
            </Timeline.Item>
          </Timeline>
        </section>
      </main>
    </div>
  )
}

export default Home
